spring:
  application:
    name: identity
  datasource:
    url: "jdbc:mysql://localhost:3306/devteria_identity_service"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /identity

jwt:
  signer-key: "7QYECn6w5CCsZklFUhn48jkNsYCnG5fQzTfCkNZe0q+BjM80YgtMI0gy0xWQVmkk"

